#!/usr/bin/env bash

set -euo pipefail

# read meta-data from buildkite-agent
# parse a list of parameters to get and set ENV_VAR_TO_SET: <metadata to get>
# support cross-job meta-data by supporting the --job key
job_switch=''
if [[ -n "${BUILDKITE_PLUGIN_METADATA_REMOTEJOBID:-}" ]] ; then
    job_switch="--job $BUILDKITE_PLUGIN_METADATA_REMOTEJOBID"
fi

while IFS='=' read -r name _ ; do
  if [[ $name =~ ^(BUILDKITE_PLUGIN_METADATA_GET_[0-9]+) ]] ; then
    echo "fetching meta-data value [${!name}]"
    metadata_value=$(buildkite-agent meta-data get ${!name})
    echo "export ${!name}=$metadata_value"
    export ${!name}=$metadata_value  

  elif [[ $name =~ ^(BUILDKITE_PLUGIN_METADATA_GETREMOTE_[0-9]+) ]] ; then
    if [[ -z "${BUILDKITE_PLUGIN_METADATA_REMOTEJOBID:-}" ]] ; then
      echo "Missing remoteJobId value when attempting to fetch remote meta-data"
      exit 1
    else
      job_switch="--job $BUILDKITE_PLUGIN_METADATA_REMOTEJOBID"
      echo "reading meta-data from job id '$BUILDKITE_PLUGIN_METADATA_REMOTEJOBID'"
      echo "fetching meta-data value [${!name}]"
      echo "buildkite-agent meta-data get ${!name} $job_switch"
      metadata_value=$(buildkite-agent meta-data get ${!name} $job_switch)
      echo "export ${!name}=$metadata_value"
      export ${!name}=$metadata_value  
    fi
  fi
done < <(env | sort)