#!/usr/bin/env bash

set -euo pipefail

# read meta-data from buildkite-agent
# parse a list of parameters to get and set ENV_VAR_TO_SET: <metadata to get>
# support cross-job meta-data by supporting the --job key
job_switch=''
if [[ -n "${BUILDKITE_PLUGIN_METADATA_JOBID:-}" ]] ; then
    job_switch="--job $BUILDKITE_PLUGIN_METADATA_JOBID"
    echo "job_switch: $job_switch"
    echo "reading meta-data from job id '$BUILDKITE_PLUGIN_METADATA_JOBID'"
fi

while IFS='=' read -r name _ ; do
  if [[ $name =~ ^(BUILDKITE_PLUGIN_METADATA_GET_[0-9]+) ]] ; then
    echo "fetching meta-data value [${!name}]"
    metadata_value=$(buildkite-agent meta-data get ${!name} $job_switch)
    echo "export ${!name}=$metadata_value"
    export ${!name}=$metadata_value  
  fi
done < <(env | sort)